# Generated by Django 5.1.6 on 2025-04-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastepickup',
            name='assigned_picker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
