# Generated by Django 5.1.6 on 2025-03-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_alter_wastepickup_user_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wastepickup',
            name='pickup_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='wastepickup',
            name='waste_type',
            field=models.CharField(default='General Waste', max_length=50),
        ),
        migrations.AlterField(
            model_name='wastepickup',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wastepickup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
