# Generated by Django 5.1.6 on 2025-03-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoConnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastepickup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wastepickup',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
